services:
  app:
    build: .
    ports:
      - "8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/first_script
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Charisma7
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 128m

  db:
    image: postgres:latest
    container_name: POSTGRES_NEW
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: first_script
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Charisma7
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"  # cAdvisor's UI
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=notapassword

volumes:
  postgres_data:
